### ISSUE TITLE
Zugriff offline LiveVoting

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#1]
**Describe the bug**
When a live voting is offline and a user is trying to access it via the link, a system error in the browser occurs. There is no error message within ILIAS that says "Keinen Zugriff auf das Live Voting mehr." or "Abstimmung gestoppt. Das LiveVoting wurde gestoppt."

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577282.html and make sure the LiveVoting is offline
2. Try to access https://ilias-next.unibe.ch/Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting/pin.php?xlvo_pin=OI1O as a logged in user
3. Try to access https://ilias-next.unibe.ch/Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting/pin.php?xlvo_pin=OI1O when not logged in to ILIAS

**Expected behavior**
logged in: Keinen Zugriff auf das Live Voting mehr. 
not logged in: "Abstimmung gestoppt. Das LiveVoting wurde gestoppt."

**Screenshots**
You can drag and drop images into this field.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS 14.1.1 ]
 - Browser [e.g. chrome]
 - Version [e.g. 119.0.6045.159]

**Additional context**

**Comment by okaufman** [comment]
fixed by Surlabs: https://mantis.ilias.de/view.php?id=39112
