### ISSUE TITLE
Can't start live voting

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#10]
**Describe the bug**
Trying to start a live voting as an admin produces an error (coding screen)

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577282.html
2. Click on 'LiveVoting beginnen"
3. See error

**Expected behavior**
Question 1 is displayed with the buttons "Vote", "Show results", Reset (deactivated), "Questions", "Back" (deactivated) / "Forward", Fullscreen

**Screenshots**
<img width="1325" alt="Bildschirmfoto 2023-11-27 um 13 51 59" src="https://github.com/ilub-unibe-ch/LiveVoting/assets/112550466/aa79d84d-b6a2-4190-b9db-7be25698344e">

**Desktop (please complete the following information):**
OS: [e.g. iOS Sonoms 14.1]
Browser [chrome, safari]
Version [Safari 17.1, Chrome 119.0.6045.105]

**Comment by okaufman** [comment]
This Issue was fixed in mantis -> https://mantis.ilias.de/view.php?id=39122
Please retest it on ilias-next and reopen this issue if there is still a problem.
