### ISSUE TITLE
Page dropdown incorrect after switching pages

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#11]
**Describe the bug**
When you switch to the second page in the list of questions and then close the browser tab and then return to the LV, the dropdown menu in the "Inhalt" > "Verwalten" tab shows the wrong page. It's still on page 2 (as shown by the questions and the question numbers, e.g. 11-16), but the dropdown menu shows "1".

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577282.html
2. Click on "Inhalt" > "Verwalten" and go to page 2
3. Close the browser tab
4. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577282.html 
5. Click on "Inhalt" > "Verwalten" notice wrong page in dropdown

**Expected behavior**
Returning to the LV, it should either show questions 1-10 in the list and "1" in the dropdown or questions n-n and "n" in the dropdown.

**Screenshots**
![Bildschirmfoto 2023-12-01 um 11 46 41](https://github.com/ilub-unibe-ch/LiveVoting/assets/112550466/728f8403-6635-416b-b5f0-b2417296611a)

**Desktop (please complete the following information):**
OS: [e.g. iOS Sonoma 14.1]
Browser [safari]
Version [Safari 17.1]

**Comment by okaufman** [comment]
This issue seems to be fixed by removing the dropdown completely and just showing all the questions at once. 
If this fix is not goof enough please reopen the issue.
