### ISSUE TITLE
Submitting response leads to error

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#12]
**Describe the bug**
When a user tries to submit a question, a coding screen appears.

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577282.html
2. Start LV and allow votes.
3. As a user, participate in LV and click "submit" button to submit answer.

**Expected behavior**
Some kind of confirmation message.

**Screenshots**
![Bildschirmfoto 2023-12-01 um 13 12 05](https://github.com/ilub-unibe-ch/LiveVoting/assets/112550466/f419eed2-2c78-4f02-9ce6-7a11a0f91031)

**Desktop (please complete the following information):**
OS: [e.g. iOS Sonoma 14.1]
Browser [chrome]
Version [Chrome 119.0.6045.105]

**Comment by okaufman** [comment]
Dieser Error wurde gefixt

**Comment by samuelinniger** [comment]
Tritt bei mir weiterhin auf (Tn klick bei SC-MC Frage auf eine Antwort). Getestet hier: https://ilias-next.unibe.ch/goto_ilias3_unibe_fold_2577766.html

<img width="1299" alt="grafik" src="https://github.com/ilub-unibe-ch/LiveVoting/assets/60101424/957f7898-41f9-4a96-bb8d-292b8889d21a">

**Comment by okaufman** [comment]
klappt jetzt auf ilias-next
