### ISSUE TITLE
Entering PIN doesn't redirect to LV

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#13]
**Describe the bug**
When entering the LV's PIN into the PIN field on https://ilias-next.unibe.ch/Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting/pin.php and clicking "submit", the pin disappears from the box and there's no redirect to the LV.

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting/pin.php
2. Enter pin OI1O (copy/paste)
3. Click "Abschicken"/"Submit"

**Expected behavior**
The submission should redirect to the LV

**Desktop (please complete the following information):**
OS: [e.g. iOS Sonoma 14.1]
Browser [chrome]
Version [Chrome 119.0.6045.105]

**Comment by okaufman** [comment]
This issue was fixed. Please retest it on ilias-next and reopen this issue if there is still a problem.
