### ISSUE TITLE
No input field for "Freitext" questions with possible multiple answers

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#14]
**Describe the bug**
For "Freitext" questions for which the option "Mehrfache Eingaben" is activated, the participants don't see a field to input their answer(s). Only when they reload the screen does there appear a little + button which, when clicked, opens an input box.

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577282.html
2. Start LV, select question "Freitext mehrfach/einzeilig"
3. Participate in LV
5. Reload screen as participant
6. See + appear

**Expected behavior**
The + button that appears after reload should always be visible

**Screenshots**
![Bildschirmfoto 2023-12-01 um 13 29 11](https://github.com/ilub-unibe-ch/LiveVoting/assets/112550466/2e455478-a0d3-41a0-9442-e746ba93f093)

**Desktop (please complete the following information):**
OS: [e.g. iOS Sonoma 14.1]
Browser [chrome]
Version [Chrome 119.0.6045.105]

**Comment by okaufman** [comment]
This issue was fixed. Please retest it on ilias-next and reopen this issue if there is still a problem.
