### ISSUE TITLE
LV ILIAS 8: Logo in Studi-Ansicht ist kein Uni-Logo

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/LiveVoting#15]
**Describe the bug**
Siehe Screenshot. Rechts: Auf ILIAS-Next wird ein anderes Logo angezeigt. Links: auf ilias.unibe.ch wird hingegen das Uni-Bern Logo angezeigt. 
Wünschenswert ist das Unibe-Logo. 

**Screenshots**
<img width="634" alt="grafik" src="https://github.com/ilub-unibe-ch/LiveVoting/assets/60101424/4c49d606-4fd6-41b4-909c-b4c5d0227800">

**Comment by Amstutz** [comment]
@yvseiler wäre ein kleiner patch im plugin. Hatten wir bisher afaik. Brauchen/wollen wir das wirklich oder reicht hier das generische logo von Live Voting core.

**Comment by yvseiler** [comment]
Wir brauchen hier das unibe-Logo. Es gibt visuelle Sicherheit, dass sich die Leute am richtigen Ort befinden. Daher bitte gerne wieder reinpatchen.

**Comment by Amstutz** [comment]
fixed. will be pushed today (re-test tomorrow)
