### ISSUE TITLE
ILIAS Produktiv: Kein anonymer Zugriff von Smartphones aus auf Livevotings möglich

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/LiveVoting#16]
**Describe the bug**
Studis/User können mit Smartphone aktuell nicht auf Livevotings zugreifen. 

In Chrome (auf Mac) wird mir zudem eine Unsichere Verbindung gemeldet: NET::ERR_CERT_COMMON_NAME_INVALID

**Additional context**
Siehe Ticket: https://serviceportal.unibe.ch/nav_to.do?uri=u_id_task.do?sys_id=8b1b5dde471142104fb1438c736d43a0

**Comment by okaufman** [comment]
klappt wieder. Problem war auf dem loadBalancer

**Comment by samuelinniger** [comment]
Zur Doku, noch eine Rückmeldung vom User, der sich im Ticket (oben verlinkt) gemeldet hat:

_Heute Morgen (Freitag) haben wir versucht, wieder mittels QR zu den Fragen zu gelangen (bis ca 10:30), was NICHT ging (Server not reachable o.ä.).
So gegen 11:30 bis jetzt geht es wieder. Instabil?_

Ich selber werde das auch noch beobachten und habe dem User geschrieben, dass er sich auch nochmals melden soll, wenn ihm etwas auffällt. Issue kann aber geschlossen bleiben.

**Comment by samuelinniger** [comment]
Funktioniert leider nicht mehr. Jetzt scheint es eine Issue mit dem Link zu geben. Es wird diese Meldung angezeigt.
Eingegebener Link: https://vote.unibe.ch/AB0X
Daraus macht der Browser: https://ilias.unibe.ch/Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting/pinphp?xlvo_pin=.AB0X

<img width="700" alt="grafik" src="https://github.com/ilub-unibe-ch/LiveVoting/assets/60101424/a8b5d12d-71fa-43cc-b97b-6f8949e28ed8">

**Comment by samuelinniger** [comment]
Könnte auch ein Webp Problem sein
Zugriff scheint auf webp3 zu funktionieren, aber nicht auf webp7

**Comment by okaufman** [comment]
Das sollte jetzt wieder klappen
