### ISSUE TITLE
ILIAS Produktiv: Kein Zugriff auf Livevoting über einzelne Wepns

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/LiveVoting#17]
Fehlermeldung auf Webpn6:

The voting is currently unavailable.

[back](https://ilias.unibe.ch/)
#0 /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting/src/Pin/xlvoPin.php(101): LiveVoting\Pin\xlvoPin::checkPinAndGetObjIdWithCache('.G28I', true) #1 /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting/pin.php(31): LiveVoting\Pin\xlvoPin::checkPinAndGetObjId('.G28I') #2 {main}

**Comment by okaufman** [comment]
Ich konnte das Problem mit dem . beheben
