### ISSUE TITLE
LV ILIAS 8: Logo fehlt, in Ansicht "Neues Livevoting hinzufügen" 

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/LiveVoting#18]
Tritt auf beim/vor dem Anlegen eines neuen LV (Neues Objekt Hinzufügen --> LiveVoting).

<img width="865" alt="grafik" src="https://github.com/ilub-unibe-ch/LiveVoting/assets/60101424/3db6b8dd-075e-4da7-9eba-d6e4ea4ff1e4">

**Comment by Amstutz** [comment]
Reported hier: https://mantis.ilias.de/view.php?id=41645

**Comment by Amstutz** [comment]
PR created: https://github.com/surlabs/LiveVoting/pull/9
