### ISSUE TITLE
Zugriff als eingeloggter User mit Einstellung "Abstimmung ohne Login" deaktiviert

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#2]
**Describe the bug**
Wenn "Abstimmung ohne Login" deaktiviert ist, kann ein eingeloggter User nicht via Kurs-Objekt auf das LiveVoting zugreifen, bzw. der Zugriff produziert ein Code-Fenster

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577282.html 
2. Abstimmung ohne Login deaktivieren
3. Als teststudent2 auf ilias-next einloggen
4. Zum Kursraum gehen: https://ilias-next.unibe.ch/goto_ilias3_unibe_crs_2577281.html und auf LiveVoting zugreifen

**Expected behavior**
via Kurs-Objekt kann abgestimmt werden. Die User werden gehasht (Code).

**Screenshots**
You can drag and drop images into this field.
![Bildschirmfoto 2023-11-24 um 15 53 21](https://github.com/ilub-unibe-ch/LiveVoting/assets/112550466/416d4da1-c83e-456f-83aa-fd8df36a2584)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS 14.1.1 ]
 - Browser [e.g. chrome]
 - Version [e.g. 119.0.6045.159]

**Additional context**

**Comment by okaufman** [comment]
This should be fixed with this->https://mantis.ilias.de/view.php?id=39114
