### ISSUE TITLE
ILIAS 8 Livevoting: Whoops, wenn ich in einem laufenden LV bei einer Prioritäten-Frage die Browserseite neu lade

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/LiveVoting#21]
**Describe the bug**
Ich habe als Kursadmin bei einem laufenden Livevoting bei einer Frage des Typs "Prioritäten" die Resultate eingeblendet.
Wenn ich dann - bei eingeblendeten Resultaten - die Seite des Browsers neu lade, wird mir dieser Woops anzeigt: "Unsupported Operand types: array + int"

Getestet hier: https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2578265.html
Jetzt scheint irgendetwas defekt/freezed zu sein bei der Frage. Wenn ich das LV nochmals aufrufe, das LV starte und zur Frage navigiere, werden mir keine Resultate angezeigt bzw. der Bereich ist eingefroren, siehe Link oben. 

**Screenshots**
<img width="1286" alt="grafik" src="https://github.com/ilub-unibe-ch/LiveVoting/assets/60101424/125f5f85-8708-4cb6-a567-0fe55a08ab66">

https://github.com/ilub-unibe-ch/LiveVoting/assets/60101424/9237fcba-c455-45d3-a0de-bdc8c50b8182

**Comment by okaufman** [comment]
fixed
