### ISSUE TITLE
LV auf ILIAS-Next: Klick auf Button "Erstellen" führt nicht zurück auf die Listenansicht der LV-Fragen

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/LiveVoting#22]
**Describe the bug**
Im Tab "Verwalten" können neue LV-Fragen hinzugefügt werden. 
Wenn ich einen beliebigen Fragetypus wähle und die Frage-Einstellungen ausfülle, kann ich die Frage mit einem Klick auf den Button "Erstellen" sichern. 
Bug: Der User verbleibt aber in der Editier-Ansicht. Wenn der User nochmals auf "Erstellen" klickt, werden weitere (gleichnamige) LV-Fragen erstellt. 

**Expected behavior**
Wie in der ILIAS-7 Pluginversion: 
Nach Klick auf "Erstellen" soll das Plugin immer zurück auf die Listenansicht mit den bereits erstellen LV-Fragen führen (Untertab "Verwalten")

**Screenshots**

https://github.com/user-attachments/assets/c3135503-9ca2-4ef5-b0cf-b7d83b95778b

**Comment by okaufman** [comment]
gefixt
