### ISSUE TITLE
Live Voting kann als Teilnehmende nicht geöffnet werden

### ISSUE THREAD

**Issue by yvseiler** [ilub-unibe-ch/LiveVoting#24]
**Describe the bug**
Langer Link aufrufen und QR-Code scannen führt zu weisser Seite mit Fehlermeldung "Undefined array key "language"
back".

**To Reproduce**
1. Go to https://ilias.unibe.ch/goto_ilias3_unibe_xlvo_722859.html
2. Copy URL https://ilias.unibe.ch/Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting/pin.php?xlvo_pin=8828

OR

2. Scan QR-Code

**Expected behavior**
Link war in ILIAS 7 noch vote.unibe.ch/8828 (der funktioniert jetzt aber auch nicht)

**Screenshots**
![Bildschirmfoto 2024-08-14 um 11 24 26 1](https://github.com/user-attachments/assets/3848f258-a803-4329-abf3-d159fdf40806)

Nach Aufruf des Links oder Scannen des QR-Codes
![IMG_ED12A75DFE8A-1](https://github.com/user-attachments/assets/365e5894-811f-4e39-afca-30af9685edf6)

**Desktop (please complete the following information):**
 - OS: macOS und iOS
 - Browser Chrome und Safari

**Comment by okaufman** [comment]
Neu kann man mit dem langen Link auf die korrekte Seite kommen.

**Comment by okaufman** [comment]
Jetzt haben wir wieder den kurzen Link aktiv.
Problem konnte mit diesem commit gefixt werden
 3e55dd4
