### ISSUE TITLE
Missing warning message for LV w/o questions

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#3]
**Describe the bug**
If a LV does not have any questions, there should be a warning message shown in the "contents" > "show" tab. Currently however, there's no such message.

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577286.html 
2. See missing warning message

**Expected behavior**
Warning message for admin (in tab "content" > "show") (red):
- The LiveVoting cannot be started because there are no questions yet.

**Screenshots**
<img width="943" alt="Bildschirmfoto 2023-11-27 um 10 48 38" src="https://github.com/ilub-unibe-ch/LiveVoting/assets/112550466/3a5cd0e6-02e9-4f91-9547-c48b6c408a50">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS Sonoms 14.1]
 - Browser [chrome, safari]
 - Version [Safari 17.1, Chrome 119.0.6045.105]

**Additional context**

**Comment by okaufman** [comment]
wurde von sulabs gefixt. https://mantis.ilias.de/view.php?id=39113
