### ISSUE TITLE
Coded error message when accessing LV w/o questions as user

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#4]
**Describe the bug**
When a course member tries to access a LV without questions, a coding screen appears rather than an error message.

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_crs_2577281.html as course member (teststudent2)
2. Click on [LiveVoting empty](https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577286.html)
3. See error

**Expected behavior**
User can access the LV but receives error message ""Voting stopped. Live voting has been stopped".

**Screenshots**
<img width="942" alt="Bildschirmfoto 2023-11-27 um 10 54 05" src="https://github.com/ilub-unibe-ch/LiveVoting/assets/112550466/de874749-7c16-4c64-9b87-8aeb2a80fcd5">

**Desktop (please complete the following information):**
OS: [e.g. iOS Sonoms 14.1]
Browser [chrome, safari]
Version [Safari 17.1, Chrome 119.0.6045.105]

**Additional context**

**Comment by okaufman** [comment]
This Issue was fixed in mantis -> https://mantis.ilias.de/view.php?id=39114
Please retest it on ilias-next and reopen this issue if there is still a problem.
