### ISSUE TITLE
Missing up/down buttons for answer options in SC/MC question

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#5]
**Describe the bug**
When setting up answer options in a SC/MC question, there are no buttons to move individual answer options up or down.

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577282.html
2. Click on 'Verwalten' and SC/MC question
3. Scroll down to answer options
4. Note missing buttons

**Expected behavior**
There should be buttons to move answer options up and down.

**Screenshots**
<img width="528" alt="Bildschirmfoto 2023-11-27 um 12 34 18" src="https://github.com/ilub-unibe-ch/LiveVoting/assets/112550466/93bbb123-6877-4387-ad8b-6fdbef1242f6">

**Desktop (please complete the following information):**
OS: [e.g. iOS Sonoms 14.1]
Browser [chrome, safari]
Version [Safari 17.1, Chrome 119.0.6045.105]

**Comment by okaufman** [comment]
This Issue was fixed in mantis -> https://mantis.ilias.de/view.php?id=39115
Please retest it on ilias-next and reopen this issue if there is still a problem.
