### ISSUE TITLE
Missing randomization option

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#6]
**Describe the bug**
In the correct order question type, the option to randomize answer options is missing.

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577282.html 
2. Click on question "Korrekte Reihenfolge" in manage tabe
3. Note missing option to randomize answers

**Expected behavior**
There should be a checkbox to activate the randomization option

**Screenshots**
<img width="586" alt="Bildschirmfoto 2023-11-27 um 12 50 03" src="https://github.com/ilub-unibe-ch/LiveVoting/assets/112550466/96b05db3-5b49-45b1-89f8-0868c3273ce8">

**Desktop (please complete the following information):**
OS: [e.g. iOS Sonoms 14.1]
Browser [chrome, safari]
Version [Safari 17.1, Chrome 119.0.6045.105]

**Comment by okaufman** [comment]
This Issue was fixed in mantis -> https://mantis.ilias.de/view.php?id=39120
Please retest it on ilias-next and reopen this issue if there is still a problem.
