### ISSUE TITLE
Answer options not included in a duplicated question

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#7]
**Describe the bug**
When duplicating a question (regardless of the question type), the duplicate does not contain the answer options that have been set up in the original.

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577282.html
2. Duplicate the SC/MC question (contains 4 answer options)
3. Open the duplicate
4. Note missing answer options (same is true for other question types as well)

**Expected behavior**
Answer options from the original should be included in the duplicate.

**Desktop (please complete the following information):**
OS: [e.g. iOS Sonoms 14.1]
Browser [chrome, safari]
Version [Safari 17.1, Chrome 119.0.6045.105]

**Comment by okaufman** [comment]
This Issue was fixed in mantis -> https://mantis.ilias.de/view.php?id=39121
Please retest it on ilias-next and reopen this issue if there is still a problem.
