### ISSUE TITLE
Adding "Zahlen schäzen" question leads to error

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#8]
**Describe the bug**
Trying to add a question of the type "Zahlen schätzen" produces an error message (coding window).

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_xlvo_2577282.html
2. Click on "Add question", select "Zahlen schätzen" and click "Select type"
3. See error

**Expected behavior**
A window should open where title, question etc. can be entered and question added.

**Screenshots**
<img width="1325" alt="Bildschirmfoto 2023-11-27 um 13 01 09" src="https://github.com/ilub-unibe-ch/LiveVoting/assets/112550466/5282d512-daee-4c9b-aef5-25f53c57abc5">

**Desktop (please complete the following information):**
OS: [e.g. iOS Sonoms 14.1]
Browser [chrome, safari]
Version [Safari 17.1, Chrome 119.0.6045.105]

**Comment by okaufman** [comment]
This Problem should also be solved now with this fix https://mantis.ilias.de/view.php?id=39122
