### ISSUE TITLE
No acces to live voting for logged in user when it hasn't been started

### ISSUE THREAD

**Issue by thielanja** [ilub-unibe-ch/LiveVoting#9]
**Describe the bug**
When a logged in course member tries to open a live voting that hasn't been started, an error message (coding screen) appears.

**To Reproduce**
1. Go to https://ilias-next.unibe.ch/goto_ilias3_unibe_crs_2577281.html as a logged in course member (test 2 student)
2. Click on "LiveVoting ILIAS8 mit Beschreibung"
3. See error

**Expected behavior**
The course member should be directed to the LV's landing page with the unibe logo (top right) and the message ""Abstimmung noch nicht freigegeben. Die Frage ist noch nicht aktiv, bisst warten. "

**Screenshots**
<img width="939" alt="Bildschirmfoto 2023-11-27 um 13 43 43" src="https://github.com/ilub-unibe-ch/LiveVoting/assets/112550466/7bdf84c8-0fe4-41bf-9f30-bd6bde4938d6">

**Desktop (please complete the following information):**
OS: [e.g. iOS Sonoms 14.1]
Browser [chrome]
Version [Chrome 119.0.6045.105]

**Comment by okaufman** [comment]
This should be fixed with this-> https://mantis.ilias.de/view.php?id=39114
